=== krka/Ardor3D/ardor3d-collada/src/main/config/binding.xsd
<?xml version='1.0' encoding='UTF-8'?>
<!--

Schema for JiBX binding definition file

This file is generally kept up to date in terms of structure, but the comments
may not match the HTML binding documentation. The HTML documentation should be
considered correct in the case of any differences.

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="binding">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="namespace" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="format" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="mapping" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    
    <xs:attribute name="add-constructors" type="xs:string"/>
    <xs:attribute name="direction" type="xs:string"/>
    <xs:attribute name="force-classes" type="xs:boolean"/>
    <xs:attribute name="forwards" type="xs:boolean"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="package" type="xs:string"/>
    <xs:attribute name="track-source" type="xs:boolean"/>
    
    <xs:attributeGroup ref="style"/>
    
  </xs:complexType>
</xs:element>

<xs:element name="include">
  <xs:complexType>
    <xs:attribute name="path" use="required" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="collection">
  <xs:complexType>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="value"/>
      <xs:element ref="structure"/>
      <xs:element ref="collection"/>
    </xs:choice>
    
    <xs:attribute name="load-method" type="xs:string"/>
    <xs:attribute name="size-method" type="xs:string"/>
    <xs:attribute name="store-method" type="xs:string"/>
    <xs:attribute name="add-method" type="xs:string"/>
    <xs:attribute name="iter-method" type="xs:string"/>
    <xs:attribute name="item-type" type="xs:string"/>
    
    <xs:attributeGroup ref="style"/>
    <xs:attributeGroup ref="name"/>
    <xs:attributeGroup ref="object"/>
    <xs:attributeGroup ref="property"/>
    <xs:attributeGroup ref="structure"/>
    
  </xs:complexType>
</xs:element>

<xs:element name="format">
  <xs:complexType>
    
    <xs:attribute name="label" type="xs:string"/>
    <xs:attribute name="type" use="required" type="xs:string"/>
    
    <xs:attributeGroup ref="string"/>
    
  </xs:complexType>
</xs:element>

<xs:element name="mapping">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="namespace" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="format" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element ref="mapping" minOccurs="0" maxOccurs="unbounded"/>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="value"/>
        <xs:element ref="structure"/>
        <xs:element ref="collection"/>
      </xs:choice>
    </xs:sequence>
    
    <xs:attribute name="class" use="required" type="xs:string"/>
    <xs:attribute name="abstract" type="xs:boolean"/>
    <xs:attribute name="extends" type="xs:string"/>
    <xs:attribute name="type-name" type="xs:string"/>
    
    <xs:attributeGroup ref="style"/>
    <xs:attributeGroup ref="name"/>
    <xs:attributeGroup ref="object"/>
    <xs:attributeGroup ref="structure"/>
    
  </xs:complexType>
</xs:element>

<xs:element name="namespace">
  <xs:complexType>
    <xs:attribute name="uri" use="required" type="xs:string"/>
    <xs:attribute name="prefix" type="xs:string"/>
    <xs:attribute name="default" type="xs:string"/>
  </xs:complexType>
</xs:element>

<xs:element name="structure">
  <xs:complexType>
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="value"/>
      <xs:element ref="structure"/>
      <xs:element ref="collection"/>
    </xs:choice>
    
    <xs:attribute name="map-as" type="xs:string"/>
    
    <xs:attributeGroup ref="name"/>
    <xs:attributeGroup ref="object"/>
    <xs:attributeGroup ref="property"/>
    <xs:attributeGroup ref="structure"/>
    <xs:attributeGroup ref="style"/>
    
  </xs:complexType>
</xs:element>

<xs:element name="value">
  <xs:complexType>
    
    <xs:attribute name="constant" type="xs:string"/>
    <xs:attribute name="format" type="xs:string"/>
    <xs:attribute name="ident" type="xs:string"/>
    <xs:attribute name="nillable" type="xs:boolean"/>
    <xs:attribute name="style" type="xs:string"/>
    
    <xs:attributeGroup ref="name"/>
    <xs:attributeGroup ref="property"/>
    <xs:attributeGroup ref="string"/>
    
  </xs:complexType>
</xs:element>

<xs:attributeGroup name="style">
  <xs:attribute name="value-style" type="xs:string"/>
</xs:attributeGroup>

<xs:attributeGroup name="name">
  <xs:attribute name="name" type="xs:string"/>
  <xs:attribute name="ns" type="xs:string"/>
</xs:attributeGroup>

<xs:attributeGroup name="property">
  <xs:attribute name="field" type="xs:string"/>
  <xs:attribute name="type" type="xs:string"/>
  <xs:attribute name="usage" type="xs:string"/>
  <xs:attribute name="test-method" type="xs:string"/>
  <xs:attribute name="get-method" type="xs:string"/>
  <xs:attribute name="set-method" type="xs:string"/>
</xs:attributeGroup>

<xs:attributeGroup name="structure">
  <xs:attribute name="allow-repeats" type="xs:boolean"/>
  <xs:attribute name="choice" type="xs:boolean"/>
  <xs:attribute name="flexible" type="xs:boolean"/>
  <xs:attribute name="label" type="xs:string"/>
  <xs:attribute name="ordered" type="xs:boolean"/>
  <xs:attribute name="using" type="xs:string"/>
</xs:attributeGroup>

<xs:attributeGroup name="string">
  <xs:attribute name="default" type="xs:string"/>
  <xs:attribute name="enum-value-method" type="xs:string"/>
  <xs:attribute name="serializer" type="xs:string"/>
  <xs:attribute name="deserializer" type="xs:string"/>
</xs:attributeGroup>

<xs:attributeGroup name="object">
  <xs:attribute name="create-type" type="xs:string"/>
  <xs:attribute name="factory" type="xs:string"/>
  <xs:attribute name="pre-set" type="xs:string"/>
  <xs:attribute name="post-set" type="xs:string"/>
  <xs:attribute name="pre-get" type="xs:string"/>
  <xs:attribute name="marshaller" type="xs:string"/>
  <xs:attribute name="nillable" type="xs:boolean"/>
  <xs:attribute name="unmarshaller" type="xs:string"/>
</xs:attributeGroup>

</xs:schema>

=== krka/Ardor3D/ardor3d-collada/src/main/config/binding.xml
<!-- 

  Copyright (c) 2008-2009 Ardor Labs, Inc.
 
  This file is part of Ardor3D.
 
  Ardor3D is free software: you can redistribute it and/or modify it 
  under the terms of its license which may be found in the accompanying
  LICENSE file or at <http://www.ardor3d.com/LICENSE>.

 -->

<binding xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="binding.xsd"
         track-source="true">
  <namespace uri="http://www.collada.org/2005/11/COLLADASchema" default="elements"/>


  <mapping class="com.ardor3d.extension.model.collada.binding.core.Collada" name="COLLADA" post-set="postset">
    <structure field="asset"/>
    <structure ordered="false">
      <collection field="libraryEffects" usage="optional" pre-set="preset">
        <structure name="library_effects" type="com.ardor3d.extension.model.collada.binding.DaeLibraries"/>
      </collection>
      <collection field="libraryMaterials" usage="optional" pre-set="preset">
        <structure name="library_materials" type="com.ardor3d.extension.model.collada.binding.DaeLibraries"/>
      </collection>
      <collection field="libraryGeometries" usage="optional" pre-set="preset">
        <structure name="library_geometries" type="com.ardor3d.extension.model.collada.binding.DaeLibraries"/>
      </collection>
      <collection field="libraryVisualScenes" usage="optional" pre-set="preset">
        <structure name="library_visual_scenes" type="com.ardor3d.extension.model.collada.binding.DaeLibraries"/>
      </collection>
      <collection field="libraryNodes" usage="optional" pre-set="preset">
        <structure name="library_nodes" type="com.ardor3d.extension.model.collada.binding.DaeLibraries"/>
      </collection>
      <collection field="libraryImages" usage="optional" pre-set="preset">
        <structure name="library_images" type="com.ardor3d.extension.model.collada.binding.DaeLibraries"/>
      </collection>
      <collection field="libraryControllers" usage="optional" pre-set="preset">
        <structure name="library_controllers" type="com.ardor3d.extension.model.collada.binding.DaeLibraries"/>
      </collection>
      <collection field="libraryAnimations" usage="optional" pre-set="preset">
        <structure name="library_animations" type="com.ardor3d.extension.model.collada.binding.DaeLibraries"/>
      </collection>

      <!-- TODO: -->
      <structure name="library_animation_clips" usage="optional"/>
      <structure name="library_cameras" usage="optional"/>
      <structure name="library_force_fields" usage="optional"/>
      <structure name="library_lights" usage="optional"/>
      <structure name="library_physics_materials" usage="optional"/>
      <structure name="library_physics_models" usage="optional"/>
      <structure name="library_physics_scenes" usage="optional"/>
    </structure>

    <structure name="scene" field="scene" type="com.ardor3d.extension.model.collada.binding.core.DaeScene" usage="optional"/>
    <structure name="extra" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.DaeLibraries" abstract="true" pre-set="postsetSpecifiedInAbstract">
    <structure field="asset" usage="optional"/>
    <collection field="libraries" pre-set="preset" post-set="postset"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.core.DaeController" name="controller" post-set="postset">
    <value name="id" set-method="setId" get-method="getId" style="attribute" usage="optional"/>
    <value name="name" set-method="setName" get-method="getName" style="attribute" usage="optional"/>
    <structure name="asset" usage="optional"/>
    <structure field="skin" type="com.ardor3d.extension.model.collada.binding.core.DaeSkin" usage="optional"/>
    <structure name="extra" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.core.DaeSkin" name="skin" pre-set="postsetSpecifiedInAbstract">
    <value name="source" field="source" style="attribute"/>
    <structure name="bind_shape_matrix" field="bindShapeMatrix" type="com.ardor3d.extension.model.collada.binding.core.DaeSimpleFloatArray" usage="optional"/>
    <collection field="sources" item-type="com.ardor3d.extension.model.collada.binding.core.DaeSource" pre-set="preset"/>
    <structure field="joints" type="com.ardor3d.extension.model.collada.binding.core.DaeJoints"/>
    <structure field="vertexWeights" type="com.ardor3d.extension.model.collada.binding.core.DaeVertexWeights"/>
    <structure name="extra" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.core.DaeJoints" name="joints" post-set="postset">
    <collection field="inputs" pre-set="preset">
      <structure name="input" type="com.ardor3d.extension.model.collada.binding.core.DaeInputUnshared"/>
    </collection>
    <structure name="extra" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.core.DaeVertexWeights" name="vertex_weights" post-set="postset">
    <collection field="inputs" pre-set="preset">
      <structure name="input" type="com.ardor3d.extension.model.collada.binding.core.DaeInputShared"/>
    </collection>
    <structure name="vcount" field="vcount" type="com.ardor3d.extension.model.collada.binding.core.DaeSimpleIntegerArray" usage="optional"/>
    <structure name="v" field="v" type="com.ardor3d.extension.model.collada.binding.core.DaeSimpleIntegerArray" usage="optional"/>
    <structure name="extra" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.fx.DaeEffect" name="effect" post-set="postset">
    <value name="id" set-method="setId" get-method="getId" style="attribute" usage="optional"/>
    <value name="name" set-method="setName" get-method="getName" style="attribute" usage="optional"/>
    <structure name="asset" usage="optional"/>
    <structure name="profile_COMMON" field="profileCommon" type="com.ardor3d.extension.model.collada.binding.fx.DaeProfileCommon"/>
    <structure name="extra" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.fx.DaeImage" name="image" post-set="postset">
    <value name="id" set-method="setId" get-method="getId" style="attribute" usage="optional"/>
    <value name="name" set-method="setName" get-method="getName" style="attribute" usage="optional"/>
    <value name="format" field="format" style="attribute" usage="optional"/>
    <value name="height" field="height" style="attribute" usage="optional"/>
    <value name="width" field="width" style="attribute" usage="optional"/>
    <value name="depth" field="depth" style="attribute" usage="optional"/>
    <structure name="asset" usage="optional"/>
    <value name="data" field="data" usage="optional"/>
    <value name="init_from" field="initFrom" usage="optional"/>
    <structure name="extra" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.fx.DaeMaterial" name="material" post-set="postset">
    <value name="id" set-method="setId" get-method="getId" style="attribute" usage="optional"/>
    <value name="name" set-method="setName" get-method="getName" style="attribute" usage="optional"/>
    <structure name="asset" usage="optional"/>
    <structure name="instance_effect" field="instanceEffect" type="com.ardor3d.extension.model.collada.binding.fx.DaeInstanceEffect"/>
    <structure name="extra" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.fx.DaeInstanceEffect" abstract="true" post-set="postsetSpecifiedInAbstract">
    <value name="sid" set-method="setSid" get-method="getSid" style="attribute" usage="optional"/>
    <value name="name" set-method="setName" get-method="getName" style="attribute" usage="optional"/>
    <value name="url" field="url" style="attribute"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.fx.DaeProfileCommon" abstract="true" post-set="postsetSpecifiedInAbstract">
    <value name="id" set-method="setId" get-method="getId" style="attribute" usage="optional"/>
    <structure name="asset" usage="optional"/>
    <collection field="newparams" item-type="com.ardor3d.extension.model.collada.binding.fx.DaeNewparam" pre-set="preset"/>
    <structure name="technique" field="technique" type="com.ardor3d.extension.model.collada.binding.fx.DaeTechnique"/>
    <structure name="extra" usage="optional"/>
    <!--  <collection field="extras" item-type="com.ardor3d.extension.model.collada.binding.core.DaeExtra" pre-set="preset"/>
    -->
  </mapping>

  <!--

     NEED TO FIGURE OUT HOW TO GET THIS TO WORK...  I think it is right, but the Eclipse JiBX plugin does not seem to have the right classpath...

   <mapping class="com.ardor3d.extension.model.collada.binding.core.DaeExtra" name="extra" post-set="postset">
         <structure name="asset" usage="optional"/>
         <collection field="techniques">
           <structure name="technique" marshaller="org.jibx.extras.DomElementMapper" unmarshaller="org.jibx.extras.DomElementMapper"->
         </collection>
   </mapping>
  -->

  <mapping class="com.ardor3d.extension.model.collada.binding.fx.DaeNewparam" name="newparam" post-set="postset">
    <value name="sid" set-method="setSid" get-method="getSid" style="attribute" usage="optional"/>
    <structure name="surface" field="surface" usage="optional"/>
    <structure field="sampler" usage="optional"/>
  </mapping>

  <mapping class="com.ardor3d.extension.model.collada.binding.fx.DaeSurface" abstract="true" post-set="postsetSpecifiedInAbstract">
    <value name="type" set-method="setTypeFromCollada" get-method="getTypeAsCollada" style="attribute" usage="optional"/>
    <collection field="initFroms" usage="optional" pre-set="preset">
